# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f25cd1aa63afde96ec00f8fea0310227"
name = "MQ: Omnichannel Pop-upsV2"
application_url = "https://mq-omnichannel-pop-ups.onrender.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_content,read_discounts,read_online_store_navigation"
optional_scopes = [ ]
use_legacy_install_flow = false

[app_proxy]
url = "https://mq-omnichannel-pop-ups.onrender.com"
subpath = "mq-popups"
prefix = "apps"

[product.metafields.app.demo_info]
type = "single_line_text_field"
name = "Demo Source Info"
description = "Tracks products created by the Shopify app template for development"

  [product.metafields.app.demo_info.access]
  admin = "merchant_read_write"

[metaobjects.app.example]
name = "Example"
description = "An example metaobject definition created by this template"

  [metaobjects.app.example.access]
  admin = "merchant_read_write"

[metaobjects.app.example.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.example.fields.description]
name = "Description"
type = "multi_line_text_field"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[auth]
redirect_urls = [
  "https://mq-omnichannel-pop-ups.onrender.com/auth/callback"
]

[build]
automatically_update_urls_on_dev = false
